"""
Multi-Modal Marketplace Intelligence — Prototype Dashboard
==========================================================
A Streamlit demonstration interface for the thesis system: it takes a product,
a marketplace, and code-mixed consumer comments, and returns (a) a sentiment
reading, (b) a price / volatility forecast comparing the fusion model against a
price-only control, and (c) an early-warning risk badge.

IMPORTANT — this is a PROTOTYPE. The inference functions below use lightweight
PLACEHOLDER logic so the interface runs before the real models are trained. The
outputs are ILLUSTRATIVE and must not be reported as model results. The three
functions marked `# >>> INTEGRATION HOOK` are where you plug in the trained
AfriBERTa+LAFT classifier, the LSTM price branch, and the late-fusion head.

Run locally:   streamlit run app.py
Requires:      pip install -r requirements.txt
"""
import hashlib
import numpy as np
import pandas as pd
import streamlit as st

st.set_page_config(page_title="Marketplace Intelligence", page_icon="📊", layout="wide")

# ----------------------------- styling -----------------------------
st.markdown("""
<style>
  .block-container {padding-top: 2rem; max-width: 1200px;}
  h1, h2, h3 {color: #1F2933; font-family: 'Helvetica Neue', Arial, sans-serif;}
  .banner {background:#FFF7ED;border:1px solid #FDBA74;border-radius:10px;
           padding:10px 16px;color:#9A3412;font-size:0.9rem;margin-bottom:1rem;}
  .badge {display:inline-block;padding:8px 18px;border-radius:999px;color:#fff;
          font-weight:700;font-size:1.05rem;}
  .r-high{background:#DC2626;} .r-med{background:#D97706;} .r-low{background:#059669;}
  .card {background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;padding:16px 18px;}
  .sub {color:#64748B;font-size:0.9rem;}
</style>
""", unsafe_allow_html=True)

st.title("Multi-Modal Marketplace Intelligence")
st.markdown("<div class='sub'>Cross-lingual sentiment and price dynamics for anticipatory pricing intelligence</div>",
            unsafe_allow_html=True)
st.markdown("<div class='banner'>🔬 <b>Prototype / demonstration.</b> Outputs are generated by "
            "placeholder logic for interface demonstration only — they are <b>not</b> predictions "
            "from the trained models. Replace the marked inference hooks with the real models to go live.</div>",
            unsafe_allow_html=True)

# ----------------------------- placeholder inference -----------------------------
# Small illustrative code-mixed lexicon (English / Nigerian Pidgin / Hausa).
POS = {"good","fine","sweet","correct","nice","love","better","fast","original","sharp",
       "quality","affordable","recommend","kyau","lafiya","madness","wonderful","worth"}
NEG = {"bad","scam","fake","slow","expensive","wahala","rubbish","poor","disappointed",
       "waste","delay","broken","costly","overpriced","yawa","terrible","cheat","nonsense"}

def mock_sentiment(comments):
    # >>> INTEGRATION HOOK 1: replace with AfriBERTa + LAFT classifier.
    #     return per-comment labels + the daily net-sentiment index S.
    rows = []
    for c in [c for c in comments if c.strip()]:
        toks = set(c.lower().replace(",", " ").replace(".", " ").split())
        p, n = len(toks & POS), len(toks & NEG)
        label = "Positive" if p > n else "Negative" if n > p else "Neutral"
        rows.append({"comment": c.strip(), "prediction": label})
    df = pd.DataFrame(rows)
    if df.empty:
        return df, 0.0, {"Positive": 0, "Negative": 0, "Neutral": 0}
    counts = df["prediction"].value_counts().to_dict()
    for k in ("Positive", "Negative", "Neutral"):
        counts.setdefault(k, 0)
    S = (counts["Positive"] - counts["Negative"]) / max(1, len(df))   # net index in [-1, 1]
    return df, S, counts

def mock_price_forecast(product, platform, S, horizon):
    # >>> INTEGRATION HOOK 2 & 3: replace with the LSTM price branch + late-fusion head.
    #     history -> control (price-only) forecast; fusion adds the sentiment signal.
    seed = int(hashlib.md5(f"{product}|{platform}".encode()).hexdigest(), 16) % (2**32)
    rng = np.random.default_rng(seed)
    base = rng.uniform(8000, 60000)
    hist = base + np.cumsum(rng.normal(0, base * 0.012, 40))
    dates = pd.date_range(end=pd.Timestamp.today().normalize(), periods=40)
    drift_ctrl = rng.normal(0, base * 0.010, horizon).cumsum()
    drift_fuse = drift_ctrl + np.linspace(0, S * base * 0.05, horizon)  # sentiment nudge
    fut = pd.date_range(start=dates[-1] + pd.Timedelta(days=1), periods=horizon)
    last = hist[-1]
    df = pd.DataFrame(index=dates.append(fut))
    df["history"] = list(hist) + [np.nan] * horizon
    df["control (price-only)"] = [np.nan] * 40 + list(last + drift_ctrl)
    df["fusion (sentiment+price)"] = [np.nan] * 40 + list(last + drift_fuse)
    vol = float(np.std(np.diff(hist) / hist[:-1]))
    return df, vol, last, float(last + drift_fuse[-1])

def risk_badge(S, vol):
    score = (vol * 4) + max(0, -S) * 0.6
    if score > 0.6 or S < -0.4:  return "HIGH", "r-high", "Elevated volatility / negative sentiment"
    if score > 0.3 or S < -0.1:  return "MEDIUM", "r-med", "Moderate volatility expected"
    return "LOW", "r-low", "Stable outlook"

# ----------------------------- sidebar inputs -----------------------------
with st.sidebar:
    st.header("Inputs")
    product = st.text_input("Product / SKU", "5kg rice")
    platform = st.selectbox("Marketplace", ["Jumia", "Konga", "Temu"])
    horizon = st.slider("Forecast horizon (days)", 3, 21, 7)
    st.markdown("**Consumer comments** (code-mixed)")
    comments_raw = st.text_area("one per line", height=160,
        value="This rice na correct, sweet well well\n"
              "Price don too cost, wahala\n"
              "Original product, fast delivery, e good\n"
              "Last one I bought was fake, scam")
    run = st.button("Run analysis", type="primary", use_container_width=True)

# ----------------------------- main panels -----------------------------
if run:
    comments = comments_raw.splitlines()
    sent_df, S, counts = mock_sentiment(comments)
    price_df, vol, last, fcast = mock_price_forecast(product, platform, S, horizon)
    level, css, msg = risk_badge(S, vol)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Net sentiment index", f"{S:+.2f}", help="(positive − negative) / total")
    c2.metric(f"Current price ({platform})", f"₦{last:,.0f}")
    c3.metric(f"{horizon}-day forecast", f"₦{fcast:,.0f}", f"{(fcast/last-1)*100:+.1f}%")
    c4.metric("Daily volatility", f"{vol*100:.1f}%")

    st.markdown("### Decision intelligence")
    st.markdown(f"<span class='badge {css}'>EARLY WARNING: {level} RISK</span>"
                f"&nbsp;&nbsp;<span class='sub'>{msg}</span>", unsafe_allow_html=True)
    st.caption("Illustrative (prototype) — derived from placeholder sentiment and price logic.")

    left, right = st.columns([3, 2])
    with left:
        st.markdown("### Price dynamics & forecast")
        st.line_chart(price_df, height=320)
        st.caption("History with price-only control vs. sentiment+price fusion forecast (illustrative).")
    with right:
        st.markdown("### Sentiment")
        st.bar_chart(pd.DataFrame.from_dict(counts, orient="index", columns=["count"]), height=200)
        if not sent_df.empty:
            st.dataframe(sent_df, use_container_width=True, hide_index=True)
else:
    st.info("Set the inputs in the sidebar and click **Run analysis**.")
